name: 'Setup OpenTofu'
description: 'Sets up OpenTofu CLI in your GitHub Actions workflow.'
author: 'm0un10'
inputs:
  tofu_version:
    default: main
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: opentofu/opentofu
        path: opentofu
        ref: ${{ inputs.tofu_version }}
    - uses: actions/setup-go@v4
      with:
        go-version-file: opentofu/go.mod
        cache-dependency-path: opentofu/go.sum
    - shell: bash
      working-directory: opentofu
      run: |-
        temp_path=${RUNNER_TEMP:-/tmp}
        go build -o ./tofu .
        cp ./tofu ${temp_path}
        echo ${temp_path} >> $GITHUB_PATH
branding:
  icon: 'terminal'
  color: 'yellow'
