inputs:
  tofu_version:
    default: main
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: opentofu/opentofu
        path: opentofu
        ref: ${{ inputs.version }}
    - uses: actions/setup-go@v4
      with:
        go-version-file: opentofu/go.mod
        cache-dependency-path: opentofu/go.sum
    - shell: bash
      working-directory: opentofu
      run: |-
        go install
